### ISSUE TITLE
Basic user honor system for Discord's servers

### ISSUE THREAD

**Issue by krzypecu** [krzypecu/DiscordPython-Bot#24]
**Describe the solution you'd like**
Propose a solution to user honor system. Make other features depend on this system.

**Comment by Noverewana** [comment]
Did the most important parts of the honor system.
When the user write something in the chat he gets experience. 
When his experience meets a certain value based on his current level, his level rises by 1.
Commands:
-rank - shows current level, experience and experience required for the next level;
-add_exp - adds experience to a user;
-add_lvl - adds levels to a user;
Not closing, because of plans for improvements.
